---
driver:
  name: docker
  hostname: poppy.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: poppy
  log_level: info
  state_top:
    base:
      "*":
        - poppy
  pillars:
    top.sls:
      base:
        "*":
          - poppy
  grains:
    noservices: True


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu


verifier:
  name: inspec
  sudo: true


suites:
  - name: default
  #  provisioner:
  #    pillars-from-files:
  #      poppy.sls: tests/pillar/default.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
